#!/bin/bash

# Get the location of the current script
BASE_DIRECTORY=$(cd `dirname $0` && pwd)

# In case we're symlinked at /usr/local/bin or something.
if [ "$(uname)" == "Darwin" ]; then
    RESOLVED_DIRECTORY=`readlink $BASE_DIRECTORY/clash`
else
    RESOLVED_DIRECTORY=`readlink -f $BASE_DIRECTORY/clash`
fi

# Remove the filename
DIRECTORY=`dirname $RESOLVED_DIRECTORY`

# The first argument to main.js is the class path of CLJS files.
node "$DIRECTORY/main.js" "$DIRECTORY/lib" $1


