#!/bin/bash

BASE_DIRECTORY=$(cd `dirname $0` && pwd)               # Get the location of the current script
RESOLVED_DIRECTORY=`readlink $BASE_DIRECTORY/clash`    # In case we're symlinked at /usr/local/bin or something.
DIRECTORY=`dirname $RESOLVED_DIRECTORY`                # Remove the filename

echo $DIRECTORY

# The first argument to main.js is the class path of CLJS files.
node "$DIRECTORY/main.js" "$DIRECTORY/lib" $1


